### ISSUE TITLE
Usage statistics section on marketing page

### ISSUE THREAD

**Issue by raae** [queen-raae/prune-your-follows#43]
It would be cool to pull in the number of unfollowed across users and the number of users for a little statistics section on the marketing page. 

- [x] Create a Gatsby node inside sourceNodes with fields "unfollowedCount" and "userCount" - hard coded to a random number - @olavea 
- [ ] Ask xata for the numbers and swap the hard coded numbers for those - @olavea (but @raae will give you the xata query)
- [x] Create the marketing section - @raae 
- [x] Hook the marketing section to the Gatsby data node - @olavea

**Comment by raae** [comment]
For reference, something like this. Just with out numbers!

<img width="1365" alt="CleanShot 2022-12-05 at 09 58 26@2x" src="https://user-images.githubusercontent.com/478531/205596039-9568154d-6632-4241-bb45-acebfb6f62cc.png">

**Comment by olavea** [comment]
```js


  createNode({
    id: 10,
    unfollowedCount: 10,
    userCount: 10,
    internal: {
      type: "statsCount",
      contentDigest: createContentDigest,
    },
  });

```

**Comment by raae** [comment]
To get the number from Xata:
´´´
const xata = getXataClient();

const result = await xata.db.accounts.aggregate({
  unfollowsTotal: {
    count: {
      filter: {
        unfollowed: { $ge: new Date("2022-11-03") },
      },
    },
  },
  usersTotal: {
    uniqueCount: {
      column: "followed_by",
    },
  },
});

const unfollowsTotal = result.aggs.unfollowsTotal
const usersTotal = result.aggs.usersTotal

// Use unfollowsTotal and usersTotal when creating node
```
